In [1]:
'''
1. Given customer bank saving data customer-savings.txt, please answer the
following questions using Python programming.
1. What’s the average balance for male and female?
2. What’s the average balance for white collar and blue collar in England?
Data columns in customer-savings.txt (separated by comma):
Customer ID, Customer Name, Customer Surname, Gender, Age, Region, Job
Classification, Date joined, Balance
100000001,Simon,Walsh,Male,21,England,White Collar,05.Jan.15,113810.15
100000003,Liam,Brown,Male,46,England,White Collar,07.Jan.15,101536.83
'''

fh = open('customer-savings.txt', 'r')
countM = 0
countF = 0
totalMaleBalance = 0
totalFemaleBalance = 0

lines = fh.readlines()
myList = []

for line in lines:
    myList.append(line.split(','))


for i in myList:
    if(i[3] == 'Male'):
        countM += 1
        balance = i[-1]
        balance = balance.replace("\n", "")
        totalMaleBalance += float(balance)
    else:
        countF += 1
        balance = i[-1]
        balance = balance.replace("\n", "")
        totalFemaleBalance += float(balance)
        
print("Average Balance for Male :", (totalMaleBalance/countM))
print("Average Balance for Female :", (totalFemaleBalance/countF))


white = 0
blue = 0
whiteBalance = 0
blueBalance = 0

for i in myList:
    if(i[5]=='England'):
        if(i[6] == 'White Collar'):
            white += 1
            balance = i[-1]
            balance = balance.replace("\n", "")
            whiteBalance += float(balance)
        elif(i[6] == 'Blue Collar'):
            blue += 1
            balance = i[-1]
            balance = balance.replace("\n", "")
            blueBalance += float(balance)
print("\n")        
print("Average Balance for White Collar in England :", (whiteBalance/white))
print("Average Balance for Blue Collar in England :", (blueBalance/blue))

Average Balance for Male : 40018.00891454967
Average Balance for Female : 39471.89511627909


Average Balance for White Collar in England : 39156.30570952698
Average Balance for Blue Collar in England : 38567.841569767465

In [5]:
'''
2. Combine multiple files
Use Python programming to combine two text files: customer-status.txt and
sales.txt

Data columns in customer-status.txt (separated by comma):
Account Number, Name, Status
527099,Sanford and Sons,bronze

Data columns in sales.txt (separated by comma):
Account Name, Name, SKU, Quantity, Unit Price, Ext Price, Date
163416,Purdy-Kunde,S1-30248,19,65.03,1235.57,2014-03-01 16:07:40
527099,Sanford and Sons,S2-82423,3,76.21,228.63,2014-03-01 17:18:01

After you combine, you will see the following:
527099,Sanford and Sons,S2-82423,3,76.21,228.63,2014-03-01 17:18:01,bronze
'''
fh = open('customer-status.csv', 'r')
fh1 = open('sales.csv', 'r')

lines = fh.readlines()
lines1 = fh1.readlines()

for line in lines:
    print(line)

account number,name,status

740150,Barton LLC,gold

714466,Trantow-Barrows,silver

218895,Kulas Inc,bronze

307599,"Kassulke, Ondricka and Metz",bronze

412290,Jerde-Hilpert,bronze

729833,Koepp Ltd,silver

146832,Kiehn-Spinka,silver

688981,Keeling LLC,silver

786968,"Frami, Hills and Schmidt",silver

239344,Stokes LLC,gold

672390,Kuhn-Gusikowski,silver

141962,Herman LLC,gold

424914,White-Trantow,silver

527099,Sanford and Sons,bronze

642753,Pollich LLC,bronze

257198,"Cronin, Oberbrunner and Spencer",gold

In [ ]:
'''myList = []
myList1 = []

for line in lines:
    myList.append(line.split(','))
    
for i in myList:
    i[-1] = i[-1].replace('\n', '')

    
for line in lines1:
     myList1.append(line.split(','))

for i in myList1:
    i[-1] = i[-1].replace('\n','')

print(len(myList))'''